# [START runtime]
runtime: nodejs16
# [END runtime]

# [START handlers]
handlers:
  - url: /static
    secure: never
    static_dir: build/static

  - url: /(.*\.(json|ico|png|mp4|PNG|js|svg))$
    secure: never
    static_files: build/\1
    upload: build/.*\.(json|ico|png|mp4|PNG|js|svg)$

  - url: /.*
    secure: never
    static_files: build/index.html
    upload: build/index.html
# [END handlers]
